// Generated by CoffeeScript 1.3.2-pre
(function() {
  var background, building, buildings, foreground, i, numbuildings, origin, pos, rect, size, street;

  origin = new Point(0, 0);

  size = new Size(10, 10);

  rect = new Path.Rectangle(origin, size);

  rect.fillColor = 'red';

  foreground = project.activeLayer;

  street = new Path;

  street.strokeColor = 'black';

  street.strokeWidth = 10;

  street.add(new Point(view.bounds.left, view.bounds.bottom));

  street.add(new Point(view.bounds.right, view.bounds.bottom));

  background = new Layer;

  background.moveBelow(foreground);

  numbuildings = 150;

  buildings = (function() {
    var _i, _results;
    _results = [];
    for (i = _i = 0; 0 <= numbuildings ? _i <= numbuildings : _i >= numbuildings; i = 0 <= numbuildings ? ++_i : --_i) {
      size = new Size([Math.floor((Math.random() * 21) + 5), Math.floor((Math.random() * 51) + 10)]);
      pos = new Point([Math.floor((Math.random() * view.bounds.width - size.width) + view.bounds.left), view.bounds.bottom - size.height]);
      building = new Path.Rectangle(pos, size);
      building.strokeColor = 'black';
      building.fillColor = 'blue';
      _results.push(building);
    }
    return _results;
  })();

}).call(this);
