// Generated by CoffeeScript 1.3.2-pre
(function() {
  var drawBackGround, drawForeGround, drawSky, randColor, randNum;

  randColor = function() {
    var i, letters;
    letters = '0123456789ABCDEF'.split('');
    return '#' + ((function() {
      var _i, _results;
      _results = [];
      for (i = _i = 1; _i <= 6; i = ++_i) {
        _results.push(letters[Math.round(Math.random() * 15)]);
      }
      return _results;
    })()).join('');
  };

  randNum = function(min, max) {
    return Math.floor((Math.random() * (max - min + 1)) + min);
  };

  drawForeGround = function() {
    var foreground, street;
    foreground = new Layer;
    street = new Path;
    street.strokeColor = 'black';
    street.strokeWidth = 10;
    street.add(new Point(view.bounds.left, view.bounds.bottom));
    street.add(new Point(view.bounds.right, view.bounds.bottom));
    return foreground;
  };

  drawBackGround = function() {
    var background, building, buildings, i, numbuildings, pos, size;
    background = new Layer;
    numbuildings = 150;
    buildings = (function() {
      var _i, _results;
      _results = [];
      for (i = _i = 0; 0 <= numbuildings ? _i <= numbuildings : _i >= numbuildings; i = 0 <= numbuildings ? ++_i : --_i) {
        size = new Size([randNum(10, 50), randNum(20, 120)]);
        pos = new Point([randNum(view.bounds.left, view.bounds.right - size.width), view.bounds.bottom - size.height]);
        building = new Path.Rectangle(pos, size);
        building.strokeColor = 'black';
        building.fillColor = randColor();
        _results.push(building);
      }
      return _results;
    })();
    return background;
  };

  drawSky = function() {
    var background, sky, skyGrad;
    background = new Layer;
    sky = new Path.Rectangle(view.bounds);
    skyGrad = new Gradient(['darkblue', 'darkred', 'red']);
    sky.fillColor = new GradientColor(skyGrad, view.bounds.topCenter, view.bounds.bottomCenter);
    return background;
  };

  drawSky();

  drawBackGround();

  drawForeGround();

}).call(this);
